import { describe, it, expect, vi } from 'vitest';
import path from 'path';
import fs from 'fs';
import os from 'os';

const confidenceEscalation = require('./confidenceEscalation.cjs');
const mineruNormalizer = require('./mineruNormalizer.cjs');
const documentProofread = require('./documentProofread.cjs');
const vaultSync = require('./vaultSync.cjs');
const store = require('./store.cjs');
const toolEnvelope = require('./toolEnvelope.cjs');
const cliHubRunner = require('./cliHubRunner.cjs');
const skillSynthesis = require('./skillSynthesis.cjs');

describe('MinerU Document Layout & Markdown Normalization', () => {
  it('strips page header/footer artifacts and print timestamps', () => {
    const raw = `--- Page 1 ---\nSome document content\nGenerated by User on 07/31/2026 Page 1 of 1`;
    const cleaned = mineruNormalizer.stripPageArtifacts(raw);
    expect(cleaned).not.toContain('--- Page 1 ---');
    expect(cleaned).not.toContain('Generated by User');
    expect(cleaned.trim()).toBe('Some document content');
  });

  it('normalizes section titles into Markdown headings', () => {
    const raw = `PROFESSIONAL SUMMARY\nExperienced Senior Technical Writer.\n\nWORK EXPERIENCE\nSenior Writer at AWS`;
    const normalized = mineruNormalizer.normalizeHeaders(raw);
    expect(normalized).toContain('## Professional Summary');
    expect(normalized).toContain('## Work Experience');
  });

  it('converts multi-column tab/space separated raw text into GFM Markdown tables', () => {
    const raw = `Date\tDescription\tAmount\n07/13/2026\tPMI Premium\t$124.80\n06/30/2026\tPayment Received\t$2,329.05`;
    const tableMd = mineruNormalizer.convertTabularTextToMarkdownTable(raw);
    expect(tableMd).toContain('| Date | Description | Amount |');
    expect(tableMd).toContain('| --- | --- | --- |');
    expect(tableMd).toContain('| 07/13/2026 | PMI Premium | $124.80 |');
  });

  it('runs end-to-end normalizeDocumentToMarkdown', () => {
    const raw = `[Attached Document: test.pdf]\n--- Page 1 ---\nDate   Description   Amount\n07/13/2026   PMI Premium   $124.80\n\nPROFESSIONAL SUMMARY\nExperienced writer.`;
    const normalized = mineruNormalizer.normalizeDocumentToMarkdown(raw);
    expect(normalized).toContain('## Professional Summary');
    expect(normalized).toContain('| Date | Description | Amount |');
    expect(normalized).not.toContain('--- Page 1 ---');
  });
});

describe('Attached Document Processing with MinerU Normalization', () => {
  it('extracts and normalizes attached documents', () => {
    const rawUserMsg = `[Attached Document: resume.pdf]\nContent:\n--- Page 1 ---\nPROFESSIONAL SUMMARY\nSenior Technical Writer\n\nUser Request: Proofread this`;
    const extracted = documentProofread.extractAttachedDocument(rawUserMsg);
    expect(extracted).toContain('## Professional Summary');
    expect(extracted).toContain('Senior Technical Writer');
  });
});

describe('Confidence Escalation Context Handling', () => {
  it('strips context boilerplate correctly', () => {
    const raw = `[CURRENT DATE/TIME]: Fri Aug 07 2026\n\n[REAL-TIME WEBCAM PRESENCE]: User present\n\nUser Request: How do I configure HA?`;
    const stripped = confidenceEscalation.stripContextBoilerplate(raw);
    expect(stripped).toBe('How do I configure HA?');
  });
});

describe('OpenHarness Tool-Call Self-Correction Hint Loop', () => {
  it('appends system self-correction hint on tool execution errors', () => {
    const toolName = 'home_assistant_control';
    const errorResult = JSON.stringify({ error: 'Service call failed: entity not found' });
    
    let content = errorResult;
    const isError = /\b(error|failed|exception)\b/i.test(content);
    if (isError) {
      content += `\n\n[SYSTEM HINT]: Tool '${toolName}' encountered an issue. Review the output above and attempt a self-correction with adjusted parameters or an alternative tool if applicable.`;
    }

    expect(content).toContain('[SYSTEM HINT]: Tool \'home_assistant_control\' encountered an issue.');
    expect(content).toContain('attempt a self-correction');
  });
});

describe('Markdown Vault Synchronization (memU 3-Layer Memory)', () => {
  it('synchronizes store memories, lessons, and knowledge to Vault Notes markdown files', async () => {
    const result = await vaultSync.syncToVault();
    expect(result.success).toBe(true);
    expect(fs.existsSync(result.memoryDir)).toBe(true);
    expect(fs.existsSync(path.join(result.memoryDir, 'README.md'))).toBe(true);
    expect(fs.existsSync(path.join(result.memoryDir, 'Learned_Knowledge.md'))).toBe(true);
    expect(fs.existsSync(path.join(result.memoryDir, 'Personal_Memories.md'))).toBe(true);
    expect(fs.existsSync(path.join(result.memoryDir, 'User_Lessons_&_Corrections.md'))).toBe(true);

    const readmeContent = fs.readFileSync(path.join(result.memoryDir, 'README.md'), 'utf-8');
    expect(readmeContent).toContain('Aloy Brain - Memory Vault');
  });
});

describe('CLI-Anything Structured Tool Envelope & Self-Correction', () => {
  it('wraps successful tool results in standardized envelope', () => {
    const success = toolEnvelope.wrapToolSuccess({ count: 5, items: ['a', 'b'] });
    expect(success.status).toBe('success');
    expect(success.data.count).toBe(5);
    expect(success.metadata.timestamp).toBeDefined();
  });

  it('wraps errors with codes, didYouMean candidates, and actionable recovery hints', () => {
    const error = toolEnvelope.wrapToolError('Entity not found', {
      code: 'ENTITY_NOT_FOUND',
      didYouMean: ['light.living_room_main', 'light.living_room_lamp'],
      recoveryHint: 'Use list_home_assistant_entities to confirm valid entity IDs'
    });
    expect(error.status).toBe('error');
    expect(error.code).toBe('ENTITY_NOT_FOUND');
    expect(error.didYouMean).toContain('light.living_room_main');
    expect(error.recoveryHint).toContain('list_home_assistant_entities');
  });

  it('formats agent results and embeds actionable recovery hints into system prompts', () => {
    const errorPayload = JSON.stringify({
      status: 'error',
      message: 'ROM failed to load',
      recoveryHint: 'Ensure BizHawk has SMB2 ROM loaded'
    });
    const formatted = toolEnvelope.formatAgentResult(errorPayload, 'bizhawk_read_game_state');
    expect(formatted).toContain('[SYSTEM HINT]: Tool \'bizhawk_read_game_state\' reported an issue.');
    expect(formatted).toContain('Ensure BizHawk has SMB2 ROM loaded');
  });
});

describe('CLI-Hub Runner & Ecosystem Integration', () => {
  it('guards against command injection and prohibited characters in tool names', async () => {
    const badRes = await cliHubRunner.executeCliHubTool('obsidian; rm -rf /', []);
    expect(badRes.status).toBe('error');
    expect(badRes.code).toBe('SECURITY_VIOLATION');
  });

  it('rejects empty queries with invalid argument code', async () => {
    const res = await cliHubRunner.searchCliHub('');
    expect(res.status).toBe('error');
    expect(res.code).toBe('INVALID_ARGUMENT');
  });

  it('searches CLI-Hub and finds existing community harnesses', async () => {
    const res = await cliHubRunner.searchCliHub('obsidian');
    expect(res.status).toBe('success');
    expect(res.data.query).toBe('obsidian');
    expect(res.data.results.length).toBeGreaterThan(0);
  });

  it('fetches metadata and skill info for a CLI-Hub harness', async () => {
    const info = await cliHubRunner.getCliHubInfo('obsidian');
    expect(info.status).toBe('success');
    expect(info.data.name).toBe('obsidian');
    expect(info.data.category).toBe('knowledge');
  });
});

describe('CLI-Anything Standard SKILL.md Card Generation & Auto-Export', () => {
  const sampleSkill = {
    id: 'skill-test-123',
    category: 'Smart Home & Automations',
    toolSequence: ['list_home_assistant_entities', 'control_smart_home_device'],
    exampleQuestion: 'Turn off the lights in the game room',
    occurrences: 4,
    createdAt: '2026-08-14T09:00:00.000Z',
    lastSeenAt: '2026-08-14T09:15:00.000Z'
  };

  it('formats synthesized skills into standard SKILL.md markdown with pipeline steps and guardrails', () => {
    const md = skillSynthesis.formatSkillAsSkillMd(sampleSkill);
    expect(md).toContain('---');
    expect(md).toContain('name: Aloy Skill - Smart Home & Automations');
    expect(md).toContain('category: Smart Home & Automations');
    expect(md).toContain('## 1. Intent & Trigger');
    expect(md).toContain('## 2. Deterministic Tool Execution Pipeline');
    expect(md).toContain('1. **`list_home_assistant_entities`**');
    expect(md).toContain('2. **`control_smart_home_device`**');
    expect(md).toContain('## 3. Cognitive Guardrails & Error Recovery');
  });

  it('exports synthesized skills and hub index to disk', () => {
    const tempDir = path.join(os.tmpdir(), `aloy_skills_test_${Date.now()}`);
    const res = skillSynthesis.exportSkillsToDisk(tempDir);
    expect(res.success).toBe(true);
    expect(fs.existsSync(tempDir)).toBe(true);
    expect(fs.existsSync(path.join(tempDir, 'README.md'))).toBe(true);

    const readme = fs.readFileSync(path.join(tempDir, 'README.md'), 'utf-8');
    expect(readme).toContain('Aloy Synthesized Skills Hub');

    // Clean up
    fs.rmSync(tempDir, { recursive: true, force: true });
  });
});
