// MinerU-Inspired Layout & Markdown Normalization Engine (harvested from OpenDataLab/MinerU)
// Converts raw PDF text, multi-column documents, and raw dumps into clean, LLM-ready Markdown:
// 1. Cleans page numbers, footers, and scanner metadata.
// 2. Normalizes section titles into Markdown headers (## Heading).
// 3. Converts pseudo-tabular space-aligned text into clean GFM Markdown tables (| Col1 | Col2 |).
// 4. Normalizes inline math/equations into LaTeX ($...$).

function stripPageArtifacts(text) {
  if (!text) return '';
  let cleaned = text;

  // Remove page numbers (e.g., "--- Page 1 ---", "Page 1 of 5", "1 / 10")
  cleaned = cleaned.replace(/^(---|===)?\s*Page\s+\d+(\s+(of|\/)\s+\d+)?\s*(---|===)?$/gim, '');
  cleaned = cleaned.replace(/^Page\s+\d+\s+of\s+\d+$/gim, '');
  
  // Remove trailing print timestamps (e.g., "Generated by User on 07/31/2026 Page 1 of 1")
  cleaned = cleaned.replace(/Generated by .*? on \d{2}\/\d{2}\/\d{4}.*$/gim, '');

  return cleaned;
}

function normalizeHeaders(text) {
  if (!text) return '';
  const lines = text.split('\n');
  const normalizedLines = [];

  // Known uppercase section headers common in resumes, technical docs, and reports
  const MAJOR_HEADERS = new Set([
    'PROFESSIONAL SUMMARY', 'SUMMARY', 'CORE COMPETENCIES', 'PROFESSIONAL EXPERIENCE',
    'WORK EXPERIENCE', 'EXPERIENCE', 'EDUCATION', 'SKILLS & TOOLS', 'SKILLS',
    'PROJECTS', 'CERTIFICATIONS', 'PUBLICATIONS', 'TRANSACTION HISTORY',
    'ACCOUNT SUMMARY', 'EXECUTIVE SUMMARY', 'SYSTEM ARCHITECTURE', 'INSTALLATION',
    'CONFIGURATION', 'TROUBLESHOOTING', 'API REFERENCE'
  ]);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) {
      normalizedLines.push('');
      continue;
    }

    // Check if line matches ALL CAPS heading format (e.g., "PROFESSIONAL EXPERIENCE")
    const cleanUpper = line.toUpperCase();
    if (MAJOR_HEADERS.has(cleanUpper) || (/^[A-Z0-9\s&/\-–]{4,50}$/.test(line) && line === cleanUpper && !line.includes('.'))) {
      normalizedLines.push(`\n## ${line.toLowerCase().replace(/\b\w/g, c => c.toUpperCase())}\n`);
    } else {
      normalizedLines.push(lines[i]);
    }
  }

  return normalizedLines.join('\n');
}

function convertTabularTextToMarkdownTable(text) {
  if (!text) return '';
  const lines = text.split('\n');
  const result = [];
  let tableBuffer = [];

  function flushTableBuffer() {
    if (tableBuffer.length < 2) {
      result.push(...tableBuffer);
      tableBuffer = [];
      return;
    }

    // Process table lines: split by 2+ spaces or tabs
    const tableRows = tableBuffer.map(row => row.split(/\t|\s{2,}/).map(cell => cell.trim()).filter(Boolean));
    const maxCols = Math.max(...tableRows.map(r => r.length));

    if (maxCols >= 2) {
      // Build GFM Markdown Table
      const headerRow = tableRows[0];
      while (headerRow.length < maxCols) headerRow.push('');
      result.push(`\n| ${headerRow.join(' | ')} |`);
      result.push(`| ${Array(maxCols).fill('---').join(' | ')} |`);

      for (let i = 1; i < tableRows.length; i++) {
        const row = tableRows[i];
        while (row.length < maxCols) row.push('');
        result.push(`| ${row.join(' | ')} |`);
      }
      result.push('');
    } else {
      result.push(...tableBuffer);
    }

    tableBuffer = [];
  }

  for (const line of lines) {
    const trimmed = line.trim();
    // Detect line with multiple tabular columns separated by 2+ spaces or tabs
    const isTabularLine = /\S+(\t|\s{2,})\S+/.test(trimmed) && !trimmed.startsWith('#') && !trimmed.startsWith('-') && !trimmed.startsWith('*');

    if (isTabularLine) {
      tableBuffer.push(line);
    } else {
      if (tableBuffer.length > 0) flushTableBuffer();
      result.push(line);
    }
  }

  if (tableBuffer.length > 0) flushTableBuffer();
  return result.join('\n');
}

function normalizeLatexMath(text) {
  if (!text) return '';
  let cleaned = text;

  // Convert legacy math markers (e.g., [MATH] ... [/MATH]) to standard inline $ ... $
  cleaned = cleaned.replace(/\[MATH\]([\s\S]*?)\[\/MATH\]/g, '$$ $1 $$');
  
  // Clean up space around inline math delimiters
  cleaned = cleaned.replace(/\$\s+([^$]+?)\s+\$/g, '$$1$');

  return cleaned;
}

/**
 * Main MinerU-style layout & document normalization pipeline.
 * Accepts raw text/PDF extraction and outputs clean LLM-ready Markdown.
 */
function normalizeDocumentToMarkdown(rawDocumentText) {
  if (!rawDocumentText || typeof rawDocumentText !== 'string') return '';

  let doc = rawDocumentText;
  doc = stripPageArtifacts(doc);
  doc = normalizeHeaders(doc);
  doc = convertTabularTextToMarkdownTable(doc);
  doc = normalizeLatexMath(doc);

  // Collapse multiple consecutive blank lines to at most two
  doc = doc.replace(/\n{3,}/g, '\n\n');

  return doc.trim();
}

/**
 * DeepDoc-inspired Structure-Aware Atomic Chunking for Apollo Vault & Document Ingestion.
 * 
 * Guarantees:
 * 1. Markdown tables are treated as atomic units (never split across chunks).
 * 2. Code blocks (``` ... ```) are treated as atomic units (never split across chunks).
 * 3. Preserves hierarchical section breadcrumbs (# -> ## -> ###) for contextual awareness.
 * 
 * @param {string} markdownText
 * @param {Object} options
 * @returns {Array<{ chunkIndex: number, content: string, sectionBreadcrumbs: string[], contentType: string, tokenEstimate: number }>}
 */
function chunkDocumentDeepDoc(markdownText, options = {}) {
  const maxTokens = options.maxTokens || 400; // ~1600 characters
  const normalized = normalizeDocumentToMarkdown(markdownText);
  if (!normalized) return [];

  const lines = normalized.split('\n');
  const blocks = [];
  let currentBlock = [];
  let currentType = 'text'; // 'text' | 'table' | 'code' | 'heading'
  let inCode = false;
  let inTable = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // 1. Code Fence Detection
    if (trimmed.startsWith('```')) {
      if (!inCode) {
        if (currentBlock.length > 0) {
          blocks.push({ type: currentType, lines: [...currentBlock] });
          currentBlock = [];
        }
        inCode = true;
        currentType = 'code';
        currentBlock.push(line);
      } else {
        currentBlock.push(line);
        inCode = false;
        blocks.push({ type: 'code', lines: [...currentBlock] });
        currentBlock = [];
        currentType = 'text';
      }
      continue;
    }

    if (inCode) {
      currentBlock.push(line);
      continue;
    }

    // 2. Table Row Detection
    if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
      if (!inTable) {
        if (currentBlock.length > 0) {
          blocks.push({ type: currentType, lines: [...currentBlock] });
          currentBlock = [];
        }
        inTable = true;
        currentType = 'table';
      }
      currentBlock.push(line);
      continue;
    } else if (inTable) {
      inTable = false;
      blocks.push({ type: 'table', lines: [...currentBlock] });
      currentBlock = [];
      currentType = 'text';
    }

    // 3. Heading Detection
    if (/^#{1,6}\s+/.test(trimmed)) {
      if (currentBlock.length > 0) {
        blocks.push({ type: currentType, lines: [...currentBlock] });
        currentBlock = [];
      }
      blocks.push({ type: 'heading', lines: [line] });
      currentType = 'text';
      continue;
    }

    // 4. Blank line separation
    if (!trimmed && currentBlock.length > 0) {
      blocks.push({ type: currentType, lines: [...currentBlock] });
      currentBlock = [];
      currentType = 'text';
      continue;
    }

    if (trimmed) {
      currentBlock.push(line);
    }
  }

  if (currentBlock.length > 0) {
    blocks.push({ type: currentType, lines: [...currentBlock] });
  }

  // Assemble blocks into structure-aware chunks with breadcrumbs
  const chunks = [];
  let currentChunkLines = [];
  let currentChunkTokens = 0;
  let activeBreadcrumbs = [];
  let currentChunkType = 'text';

  function flushChunk() {
    if (currentChunkLines.length === 0) return;
    const content = currentChunkLines.join('\n').trim();
    if (content) {
      chunks.push({
        chunkIndex: chunks.length,
        content,
        sectionBreadcrumbs: [...activeBreadcrumbs],
        contentType: currentChunkType,
        tokenEstimate: Math.ceil(content.length / 4)
      });
    }
    currentChunkLines = [];
    currentChunkTokens = 0;
    currentChunkType = 'text';
  }

  for (const block of blocks) {
    const blockContent = block.lines.join('\n');
    const blockTokens = Math.ceil(blockContent.length / 4);

    // Update active section breadcrumbs
    if (block.type === 'heading') {
      const headingLine = block.lines[0].trim();
      const match = headingLine.match(/^(#{1,6})\s+(.*)$/);
      if (match) {
        const level = match[1].length;
        const headingText = match[2].trim();
        activeBreadcrumbs = activeBreadcrumbs.slice(0, level - 1);
        activeBreadcrumbs[level - 1] = headingText;
      }
    }

    // Atomic blocks (table, code) that exceed or fit
    if (block.type === 'table' || block.type === 'code') {
      if (currentChunkTokens + blockTokens > maxTokens && currentChunkLines.length > 0) {
        flushChunk();
      }
      currentChunkLines.push(...block.lines);
      currentChunkTokens += blockTokens;
      currentChunkType = block.type;
      flushChunk();
      continue;
    }

    if (currentChunkTokens + blockTokens > maxTokens && currentChunkLines.length > 0) {
      flushChunk();
    }

    currentChunkLines.push(...block.lines);
    currentChunkTokens += blockTokens;
  }

  flushChunk();
  return chunks;
}

module.exports = {
  normalizeDocumentToMarkdown,
  chunkDocumentDeepDoc,
  stripPageArtifacts,
  normalizeHeaders,
  convertTabularTextToMarkdownTable,
  normalizeLatexMath
};
