// Canonical data store for the Aloy backend server. A single JSON file,
// matching this project's existing lightweight-storage philosophy (no
// database dependency) — reasonable at personal-assistant data volumes.
//
// This is a SEPARATE store from the desktop app's own localStorage. It is
// seeded once from the NAS backup so it starts non-empty, and becomes the
// source of truth for anything done via this server (mobile/API clients).
// Reconciling it with the desktop app's own localStorage (so there is
// truly one source of truth everywhere) is a deliberate follow-up, not
// done here.
const fs = require('fs');
const path = require('path');

const STORE_DIR = path.join(require('os').homedir(), '.aloy-server');
const STORE_PATH = path.join(STORE_DIR, 'store.json');

const DEFAULT_STORE = {
  reminders: [],
  transactions: [],
  budgets: [],
  // Workout log — harvested from norrdev/OpenGym's data model (session +
  // logged exercises), not their full program-builder/exercise-catalog
  // system. Each entry: {id, date, exercises: [{name, sets, reps, weight}],
  // notes}. Added 2026-08-23.
  workouts: [],
  // Stock ticker symbols Hermes tracks (server/stockTracker.cjs +
  // HermesEngine.getPortfolioSnapshot), the last successfully-fetched quote
  // per symbol so a chat request doesn't always have to wait on a live
  // network call, and optional share counts (set from the Hermes Financial
  // Pulse panel) used to compute per-holding and total position value —
  // {symbols: string[], shares: {SYM: number}, lastQuotes: {SYM: {price,
  // previousClose, changePercent, name, fetchedAt}}}. A symbol with no
  // entry in `shares` is tracked for price only, no value shown.
  stockPortfolio: { symbols: [], shares: {}, lastQuotes: {} },
  memories: [],
  trackedProjects: [],
  vaultDir: null,
  chats: [],
  // Log of low-confidence local answers escalated to Claude, each entry
  // {timestamp, question, claudeAnswer, embedding, fromCache}. Doubles as a
  // retrieval cache (server/confidenceEscalation.cjs checks embedding
  // similarity here before calling Claude again for a near-duplicate
  // question) and as the source for the sidebar/drawer "Claude assist"
  // status widget. Capped at MAX_ESCALATIONS_STORED entries.
  claudeEscalations: [],
  // Facts Aloy actively researched (via the research_topic/save_researched_knowledge
  // tools, server/research.cjs, OR the automated nightly teaching pipeline,
  // server/skillsDashboard.cjs's runNightlyAutoTeaching) — general knowledge,
  // not personal facts about the user, so kept separate from `memories` for
  // the same reason the AutoRipManager fact stayed a one-off there. Each entry:
  // {id, topic, summary, sources: [{url, title}], savedAt, autoGenerated?,
  // verifiedBy?}. Auto-generated entries only land here after BOTH Claude's
  // research AND an independent Gemini verification pass agree it's solid —
  // see runNightlyAutoTeaching's teachingStatus gate on claudeEscalations.
  learnedKnowledge: [],
  // Explicit user corrections ("no, actually X" / "remember that Y") — kept
  // SEPARATE from learnedKnowledge because these carry maximum trust: they
  // always override anything auto-researched on the same topic, injected
  // into every system prompt unconditionally (small expected volume, so no
  // relevance filtering needed the way learnedKnowledge gets). Each entry:
  // {id, topic, correction, createdAt}. Added 2026-08-04 (harvested from
  // KiroCrew's "lessons always win" pattern) — see save_lesson in
  // src/services/tools.js and runNightlyAutoTeaching's conflict check.
  lessons: [],
  // Recent logged tool-call sequences (server/skillSynthesis.cjs) — one
  // entry per completed turn that used at least one tool AND never touched
  // a write/confirmation-required tool (write sequences are deliberately
  // never logged here, harvested from KiroCrew's "skip sensitive/write
  // paths before skill extraction" pattern — a skill nudging the model
  // toward repeating a WRITE action automatically is a much bigger risk
  // than nudging it toward a known-good READ sequence). Capped, rolling
  // window — {timestamp, question, toolSequence, category}.
  toolCallLog: [],
  // Synthesized reusable tool-call patterns, auto-created once the same
  // category+ordered-sequence repeats MIN_OCCURRENCES_TO_SYNTHESIZE times
  // in toolCallLog — injected into the system prompt as a hint so Aloy
  // proactively follows a known-good sequence instead of rediscovering (or
  // guessing wrong) it every time. Auto-activates with no manual approval
  // step, matching this codebase's established "dashboard is a glance, not
  // a workbench" philosophy. {id, category, toolSequence, exampleQuestion,
  // occurrences, createdAt, lastSeenAt}.
  skills: [],
  // Local (not UTC) date string the automated nightly teaching pass last
  // ran — gates it to once per day. Each processed claudeEscalations entry
  // also gets its own `teachingStatus` ('confirmed'|'needs_review'|'error'|
  // 'skipped') so a run only processes entries it hasn't already looked at,
  // rather than reprocessing the whole history every night.
  lastAutoTeachingRun: null,
  // Local (not UTC) date string ('YYYY-MM-DD') the end-of-day learning
  // report was last generated for — gates the aloyServer.cjs scheduler so
  // it fires exactly once per day rather than on every periodic check.
  lastDailyReportDate: null,
  // Gates seedFromBackupIfEmpty below — see that function's comment for why
  // this exists (a real chat-data-loss bug it fixes, root-caused 2026-07-31).
  seededFromBackup: false,
  // Local (not UTC) date string ('YYYY-MM-DD') the "how's your day going"
  // system-prompt check-in was last included — gates maybeConsumeDailyCheckIn
  // below so it fires once per day, shared across desktop and mobile since
  // both read/write this same store.
  lastCheckInDate: null,
  // ISO timestamp checkpoint for the anomaly-alert poller in aloyServer.cjs
  // (maybeAlertVisionAnomalies) — the last LLM Vision event start time
  // already pushed to the phone via HA's notify.mobile_app_* service.
  // Persisted so a server restart doesn't re-alert on old events or lose
  // its place. Left null until the poller's first run initializes it to
  // "now" (never backfills alerts for pre-existing history).
  lastVisionAlertAt: null,
  // Per-service alert state for the service-outage watchdog in
  // aloyServer.cjs (runServiceWatchdog) — { [serviceName]: { alerted,
  // failCount } }. `alerted` gates transition-based alerting (fire once on
  // up→down, once on recovery, never on every poll while down); `failCount`
  // implements the consecutive-failures threshold so one flaky probe or a
  // quick service restart doesn't false-alarm. Persisted so a server
  // restart doesn't re-announce an outage that was already alerted.
  serviceHealthState: {},
  // Log of every Claude proofread pass run against a document rewrite (see
  // server/documentProofread.cjs) — {timestamp, clean, issueCount}. This is
  // how we'll know when Aloy no longer needs Claude proofreading it: once
  // the local model strings together enough consecutive clean passes (see
  // getDocumentProofreadStats' GRADUATION_STREAK below), that's the signal
  // to turn the safety net off. Capped at MAX_PROOFREAD_HISTORY entries.
  documentProofreadHistory: [],
  // Tech-news pipeline (server/newsScraper.cjs) — separate domains for
  // config (sources/interests, user-edited) vs. the resulting feed, same
  // separation as trackedProjects (config) vs. its live-fetched status.
  // newsSources: {id, url, name, linkSelector?, type?, channelId?} —
  // linkSelector is the CSS selector for article-link elements on that
  // site, passed straight to the scraper sidecar's /scrape route; omitted,
  // it falls back to a rough generic "any link with headline-length text"
  // heuristic. type: 'youtube' (auto-detected from the URL when a source
  // is added) routes through newsScraper.cjs's RSS-feed path instead of
  // the web-scrape path; channelId is that resolution's cached result so
  // it's only looked up once, not on every scrape.
  newsSources: [],
  // Free-text topics/keywords describing what's actually wanted, folded
  // into the local-model relevance prompt in scoreRelevance().
  newsInterests: [],
  // The curated feed itself, capped at MAX_NEWS_ARTICLES (see
  // newsScraper.cjs) — {id, title, url, sourceId, sourceName, relevant,
  // relevanceReason, scrapedAt}. Only relevant:true entries are meant to
  // be shown; irrelevant ones are kept briefly for scoring-quality
  // debugging, same reasoning as claudeEscalations staying instead of
  // being deleted.
  newsArticles: [],
  // ISO timestamp gate for the scheduled scrape job in aloyServer.cjs —
  // same shape as lastVisionAlertAt above.
  lastNewsScrapeAt: null,
  userProfile: {
    name: 'User',
    style: 'Concise, direct, highly technical, clean code, dark UI aesthetics.',
    instructions: 'Always address requests directly with production-ready code and optimal architecture.',
    checkInsEnabled: true
  },
  // Ruflo Harvest (ruvnet/ruflo) — Distributed Federation, SPARC Workflows, and Agent Arena
  federationPeers: [],
  sparcWorkflows: [],
  arenaTournaments: [],
  arenaStrategies: []
};

const BAK1_PATH = STORE_PATH + '.bak1';
const BAK2_PATH = STORE_PATH + '.bak2';

function atomicSaveJson(filePath, data) {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });

  const serialized = JSON.stringify(data, null, 2);
  const tmpPath = path.join(dir, `.${path.basename(filePath)}.${process.pid}.${Date.now()}.${Math.random().toString(36).slice(2)}.tmp`);

  try {
    fs.writeFileSync(tmpPath, serialized, 'utf-8');

    // Rotate rolling backups before overwriting active file
    if (fs.existsSync(filePath)) {
      try {
        if (fs.existsSync(BAK1_PATH)) {
          fs.copyFileSync(BAK1_PATH, BAK2_PATH);
        }
        fs.copyFileSync(filePath, BAK1_PATH);
      } catch (backupErr) {
        console.warn('store.cjs: snapshot rotation warning:', backupErr.message);
      }
    }

    // Atomic filesystem swap with Windows EPERM resilience
    let renamed = false;
    for (let attempt = 0; attempt < 5; attempt++) {
      try {
        fs.renameSync(tmpPath, filePath);
        renamed = true;
        break;
      } catch (renameErr) {
        if (renameErr.code === 'EPERM' || renameErr.code === 'EBUSY') {
          // Brief pause before retrying Windows lock release
          const start = Date.now();
          while (Date.now() - start < 15) {}
        } else {
          throw renameErr;
        }
      }
    }

    if (!renamed) {
      fs.copyFileSync(tmpPath, filePath);
      try { fs.unlinkSync(tmpPath); } catch {}
    }
  } catch (err) {
    if (fs.existsSync(tmpPath)) {
      try { fs.unlinkSync(tmpPath); } catch {}
    }
    throw err;
  }
}

function ensureStoreExists() {
  fs.mkdirSync(STORE_DIR, { recursive: true });
  if (!fs.existsSync(STORE_PATH)) {
    atomicSaveJson(STORE_PATH, DEFAULT_STORE);
  }
}

function tryParseStoreFile(filePath) {
  if (!fs.existsSync(filePath)) return null;
  try {
    const raw = fs.readFileSync(filePath, 'utf-8');
    if (!raw || raw.trim().length === 0) return null;
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

function load() {
  ensureStoreExists();

  // Try primary store file
  let parsed = tryParseStoreFile(STORE_PATH);

  // If corrupted or empty, attempt automated recovery from rolling snapshots
  if (!parsed) {
    console.warn('store.cjs: Primary store is corrupt or empty. Attempting snapshot recovery...');
    parsed = tryParseStoreFile(BAK1_PATH) || tryParseStoreFile(BAK2_PATH);
    if (parsed) {
      console.warn('store.cjs: Successfully recovered state from rolling backup! Restoring primary store.');
      atomicSaveJson(STORE_PATH, parsed);
    }
  }

  if (!parsed) {
    console.error('store.cjs: CRITICAL: Could not recover from store or snapshots. Using default store baseline.');
    return { ...DEFAULT_STORE };
  }

  return { ...DEFAULT_STORE, ...parsed };
}

function save(store) {
  atomicSaveJson(STORE_PATH, store);
}

// One-time seed from the NAS backup, on this server's very first run only —
// gated on the persistent seededFromBackup flag, NOT on which data arrays
// happen to be empty.
//
// BUG (root-caused 2026-07-31, was previously gated on
// `reminders/transactions/budgets/memories all empty`): a user who mostly
// just chats via the mobile app (never logging reminders/transactions/
// budgets, and whose server-side memories array independently stayed empty)
// could have those four arrays all empty while `chats` had already grown to
// several real threads. Every server restart re-ran this "isEmpty" check,
// found it true, and silently overwrote the live (larger) chats array with
// whatever the NAS backup file happened to contain AT THAT MOMENT — observed
// going from 4 chats to 1 between two backups a day apart. The flag below
// makes this genuinely fire once, ever, regardless of which arrays are
// empty on any later restart.
function seedFromBackupIfEmpty(backupPath) {
  const store = load();
  if (store.seededFromBackup || !fs.existsSync(backupPath)) return false;

  try {
    const backup = JSON.parse(fs.readFileSync(backupPath, 'utf-8'));
    save({
      reminders: backup.ollama_pro_reminders || [],
      transactions: backup.ollama_pro_transactions || [],
      budgets: backup.ollama_pro_budgets || [],
      memories: backup.ollama_pro_user_memories || [],
      trackedProjects: backup.ollama_pro_tracked_projects || [],
      vaultDir: null,
      chats: backup.ollama_pro_chats || [],
      seededFromBackup: true,
      userProfile: backup.ollama_pro_user_profile || DEFAULT_STORE.userProfile
    });
    return true;
  } catch (err) {
    console.error('Aloy server: failed to seed from backup:', err.message);
    return false;
  }
}

function localISODate(date = new Date()) {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

// Fire-once-per-local-day gate for the "how's your day going" check-in
// (added 2026-08-03) — shared by both aloyServer.cjs's buildSystemInstruction
// (mobile/API path) and electron.cjs's checkin:shouldInclude IPC handler
// (desktop path, which builds its own separate system prompt in App.jsx) —
// both need to agree on a single "already checked in today" flag against the
// one shared store.json, so whichever platform's first message of the day
// gets here first "uses up" today's check-in for both. Mutates and persists
// lastCheckInDate as a side effect of returning true.
function maybeConsumeDailyCheckIn() {
  const store = load();
  if (store.userProfile?.checkInsEnabled === false) return false;
  const today = localISODate();
  if (store.lastCheckInDate === today) return false;
  store.lastCheckInDate = today;
  save(store);
  return true;
}

// How many consecutive clean proofreads it takes before we'd consider Aloy
// "graduated" off the mandatory Claude proofread pass, and how large a
// recent-sample window to use for the clean-rate stat shown alongside it.
const GRADUATION_STREAK = 15;
const RECENT_SAMPLE_SIZE = 15;
const MAX_PROOFREAD_HISTORY = 50;

// Called from both integration points right after proofreadDocumentRewrite
// resolves (electron.cjs's document:proofread handler for desktop,
// aloyServer.cjs's maybeEscalateInBackground for mobile/API) so every
// document turn's verdict gets recorded regardless of which platform
// triggered it — both write the same store.json.
function logDocumentProofread({ clean, notes }) {
  const store = load();
  const history = store.documentProofreadHistory || [];
  const issueCount = clean ? 0 : ((notes || '').match(/^\s*\d+\./gm)?.length || 1);
  history.push({ timestamp: new Date().toISOString(), clean, issueCount });
  store.documentProofreadHistory = history.slice(-MAX_PROOFREAD_HISTORY);
  save(store);
}

function getDocumentProofreadStats() {
  const store = load();
  const history = store.documentProofreadHistory || [];
  const recent = history.slice(-RECENT_SAMPLE_SIZE);

  let cleanStreak = 0;
  for (let i = history.length - 1; i >= 0; i--) {
    if (!history[i].clean) break;
    cleanStreak++;
  }

  return {
    totalLogged: history.length,
    recentSampleSize: recent.length,
    recentCleanRate: recent.length ? Math.round((recent.filter((h) => h.clean).length / recent.length) * 100) : null,
    cleanStreak,
    graduationStreak: GRADUATION_STREAK,
    readyToGraduate: cleanStreak >= GRADUATION_STREAK,
    lastResult: history.length ? history[history.length - 1] : null
  };
}

module.exports = { load, save, seedFromBackupIfEmpty, STORE_PATH, maybeConsumeDailyCheckIn, logDocumentProofread, getDocumentProofreadStats };
