/**
 * Universal Mitosis Component Compiler for Aloy
 * Transforms .lite.jsx universal components into:
 *  - dist/react/ (Desktop React 19 & Docs)
 *  - dist/react-native/ (Mobile React Native APK)
 */

const fs = require('fs');
const path = require('path');
const mitosis = require('@builder.io/mitosis');

const SRC_DIR = path.join(__dirname, 'src');
const DIST_DIR = path.join(__dirname, 'dist');
const REACT_DIR = path.join(DIST_DIR, 'react');
const RN_DIR = path.join(DIST_DIR, 'react-native');

// Ensure output directories exist
[DIST_DIR, REACT_DIR, RN_DIR].forEach(dir => {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
});

async function compileAll() {
  console.log('⚡ Compiling universal Mitosis components for Aloy...\n');
  const files = fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.lite.jsx') || f.endsWith('.lite.tsx'));

  const exportsReact = [];
  const exportsRN = [];

  for (const file of files) {
    const baseName = file.replace(/\.lite\.[jt]sx$/, '');
    const srcPath = path.join(SRC_DIR, file);
    const code = fs.readFileSync(srcPath, 'utf8');

    console.log(`📦 Processing ${file} -> [React, React-Native]`);

    // Parse JSX into Mitosis JSON AST
    const parsed = mitosis.parseJsx(code);

    // 1. Compile to React (Web / Desktop / Docs)
    const reactOutput = mitosis.componentToReact({
      format: 'esm',
      stylesType: 'style-tag'
    })({ component: parsed });

    const reactOutPath = path.join(REACT_DIR, `${baseName}.jsx`);
    fs.writeFileSync(reactOutPath, reactOutput, 'utf8');
    exportsReact.push(`export { default as ${baseName} } from './react/${baseName}.jsx';`);

    // 2. Compile to React Native (Mobile APK)
    const rnOutput = mitosis.componentToReactNative({
      stateType: 'useState'
    })({ component: parsed });

    const rnOutPath = path.join(RN_DIR, `${baseName}.jsx`);
    fs.writeFileSync(rnOutPath, rnOutput, 'utf8');
    exportsRN.push(`export { default as ${baseName} } from './react-native/${baseName}.jsx';`);
  }

  // Write top-level barrel export files
  fs.writeFileSync(
    path.join(DIST_DIR, 'index.react.js'),
    `// Generated by Aloy Mitosis Compiler\n${exportsReact.join('\n')}\n`,
    'utf8'
  );

  fs.writeFileSync(
    path.join(DIST_DIR, 'index.rn.js'),
    `// Generated by Aloy Mitosis Compiler\n${exportsRN.join('\n')}\n`,
    'utf8'
  );

  console.log(`\n🎉 Compiled ${files.length} universal components successfully!`);
}

compileAll().catch(console.error);
